on: push
name: "release"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: bdougie/variables-in-markdown@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}`
