# Please update go version in go.mod also, if you update the go version here.
name: Tests
on:
  push:
    branches:
      - 'main'
      - 'Release*'
  pull_request:
    branches:
      - 'main'
      - 'Release*'
      - '*'
  workflow_dispatch:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8 #install the python needed
          cache: 'pip'
      - name: install python dependencies
        run: pip install -r samples/requirements.txt
      - name: Test
        run: echo '--timeout 20'
