models:
  - model_spec:
      edge_sources:
        - inputs/stripeCustomers
        - inputs/stripeCharges
        - inputs/stripeInvoices
        - inputs/stripeBalanceHistory
        - inputs/stripeSubscriptions
        - inputs/stripeRefunds
        - inputs/stripeInvoicesView
      entity_key: customer
      main_id_type: main_id
      validity_time: 24h
    model_type: id_stitcher
    name: customer_stripe_id_stitcher
#  - name: subscription_stripe_id_stitcher2
#    model_type: id_stitcher
#    model_spec:
#      edge_sources:
#        - inputs/stripeCharges
#        - inputs/stripeInvoices
#        - inputs/stripeBalanceHistory
#        - inputs/stripeSubscriptions
#        - inputs/stripeRefunds
#      entity_key: subscription
#      main_id_type: subscription_main_id
#      validity_time: 24h
#  - name: customer_stripe_features
#    model_type: feature_table_model
#    model_spec:
#      entity_key: customer
#      features:
#        - shipping_address_country
#        - shipping_address_state
#        - customer_currency
#        - payment_method_details_card_network
#        - is_delinquent
#        - has_credit_card
#        - days_since_first_sale
#        - days_since_last_purchase
#        - total_sales
#        - total_refunds
#        - total_fees
#        - total_amt_spent
#        - total_net_transaction_amount
#        - average_transaction_value
#        - highest_transaction_value
#        - total_transactions
#        - refund_count
#        - total_failed_charge_amount
#        - total_failed_charge_count
#        - sales_in_past_365_days
#        - refund_in_past_365_days
#        - fees_in_past_365_days
#        - amt_spent_in_past_365_days
#        - average_transaction_value_in_past_365_days
#        - highest_transaction_value_in_past_365_days
#        - net_transaction_amount_in_past_365_days
#        - transactions_in_past_365_days
#        - refund_count_in_past_365_days
#        - n_subscriptions_total
#        - n_plans_total
#        - n_paid_intervals
#        - n_max_renewals
#        - distinct_plans_subscribed
#        - current_amount_due_subscriptions
#        - amt_spent_subscriptions
#        - days_since_first_subscription
#        - total_active_subscriptions
#        - total_active_plans
#        - active_plan_intervals
#        - total_active_plan_amount
#      macros:
#        - inputs:
#            - timestamp_col
#          name: macro_datediff
#          value: datediff(day, date({{timestamp_col}}), to_timestamp_tz(replace('{{timestamp}}',' UTC')))
#      validity_time: 24h
#      vars:
#        - entityvar:
#            from: inputs/stripeCharges
#            name: shipping_address_country_ts
#            select: max(created)
#            where: currency is not null and currency != ''
#        - entityvar:
#            from: inputs/stripeCharges
#            name: shipping_address_country
#            select: max(billing_details_address_country)
#            where: created = shipping_address_country_ts
#        - entityvar:
#            from: inputs/stripeCharges
#            name: shipping_address_state_ts
#            select: max(created)
#            where: currency is not null and currency != ''
#        - entityvar:
#            from: inputs/stripeCharges
#            name: shipping_address_state
#            select: max(billing_details_address_state)
#            where: created = shipping_address_state_ts
#        - entityvar:
#            from: inputs/stripeCharges
#            name: customer_currency_ts
#            select: max(created)
#            where: currency is not null and currency != ''
#        - entityvar:
#            from: inputs/stripeCharges
#            name: customer_currency
#            select: max(currency)
#            where: created = customer_currency_ts
#        - entityvar:
#            from: inputs/stripeCharges
#            name: payment_method_details_card_network_ts
#            select: max(created)
#            where: currency is not null and currency != ''
#        - entityvar:
#            from: inputs/stripeCharges
#            name: payment_method_details_card_network
#            select: max(payment_method_details_card_network)
#            where: created = payment_method_details_card_network_ts
#        - entityvar:
#            from: inputs/stripeCustomers
#            name: is_delinquent
#            select: max(delinquent)
#        - entityvar:
#            from: inputs/stripeCharges
#            name: has_credit_card
#            select: max(case when (payment_method_details_card_funding = 'credit' and status = 'succeeded') then 1 else 0 end)
#        - entityvar:
#            from: inputs/stripeCharges
#            name: first_sale_time
#            select: min(created)
#            where: status = 'succeeded'
#        - entityvar:
#            name: days_since_first_sale
#            select: '{{ macro_datediff(''first_sale_time'') }}'
#        - entityvar:
#            from: inputs/stripeCharges
#            name: last_purchase_time
#            select: max(created)
#            where: status = 'succeeded'
#        - entityvar:
#            name: days_since_last_purchase
#            select: '{{ macro_datediff(''last_purchase_time'') }}'
#        - entityvar:
#            from: inputs/stripeBalanceHistory
#            name: total_sales
#            select: sum(amount)
#            where: type = 'charge'
#        - entityvar:
#            from: inputs/stripeBalanceHistory
#            name: total_refunds
#            select: sum(amount)
#            where: type = 'refund'
#        - entityvar:
#            from: inputs/stripeBalanceHistory
#            name: total_fees
#            select: sum(fee)
#        - entityvar:
#            from: inputs/stripeBalanceHistory
#            name: total_amt_spent
#            select: sum(amount)
#        - entityvar:
#            from: inputs/stripeBalanceHistory
#            name: total_net_transaction_amount
#            select: sum(net)
#        - entityvar:
#            from: inputs/stripeBalanceHistory
#            name: average_transaction_value
#            select: avg(amount)
#        - entityvar:
#            from: inputs/stripeBalanceHistory
#            name: highest_transaction_value
#            select: max(amount)
#        - entityvar:
#            from: inputs/stripeBalanceHistory
#            name: total_transactions
#            select: sum(case when type = 'charge' then 1 else 0 end)
#        - entityvar:
#            from: inputs/stripeBalanceHistory
#            name: refund_count
#            select: sum(case when type = 'refund' then 1 else 0 end)
#        - entityvar:
#            from: inputs/stripeCharges
#            name: total_failed_charge_amount
#            select: sum(amount)
#            where: status = 'failed'
#        - entityvar:
#            from: inputs/stripeCharges
#            name: total_failed_charge_count
#            select: sum(case when status = 'failed' then 1 else 0 end)
#        - entityvar:
#            from: inputs/stripeBalanceHistory
#            name: sales_in_past_365_days
#            select: sum(case when type = 'charge' then amount else 0 end)
#            where: '{{ macro_datediff(''created'') }} <= 365'
#        - entityvar:
#            from: inputs/stripeBalanceHistory
#            name: refund_in_past_365_days
#            select: sum(case when type = 'refund' then amount else 0 end)
#            where: '{{ macro_datediff(''created'') }} <= 365'
#        - entityvar:
#            from: inputs/stripeBalanceHistory
#            name: fees_in_past_365_days
#            select: sum(fee)
#            where: '{{ macro_datediff(''created'') }} <= 365'
#        - entityvar:
#            from: inputs/stripeBalanceHistory
#            name: amt_spent_in_past_365_days
#            select: sum(amount)
#            where: '{{ macro_datediff(''created'') }} <= 365'
#        - entityvar:
#            from: inputs/stripeBalanceHistory
#            name: average_transaction_value_in_past_365_days
#            select: avg(amount)
#            where: '{{ macro_datediff(''created'') }} <= 365'
#        - entityvar:
#            from: inputs/stripeBalanceHistory
#            name: highest_transaction_value_in_past_365_days
#            select: max(amount)
#            where: '{{ macro_datediff(''created'') }} <= 365'
#        - entityvar:
#            from: inputs/stripeBalanceHistory
#            name: net_transaction_amount_in_past_365_days
#            select: sum(net)
#            where: '{{ macro_datediff(''created'') }} <= 365'
#        - entityvar:
#            from: inputs/stripeBalanceHistory
#            name: transactions_in_past_365_days
#            select: sum(case when type = 'charge' then 1 else 0 end)
#            where: '{{ macro_datediff(''created'') }} <= 365'
#        - entityvar:
#            from: inputs/stripeBalanceHistory
#            name: refund_count_in_past_365_days
#            select: sum(case when type = 'refund' then 1 else 0 end)
#            where: '{{ macro_datediff(''created'') }} <= 365'
#        - entityvar:
#            from: inputs/stripeInvoicesView
#            name: n_subscriptions_total
#            select: count( distinct subscriptions_id)
#        - entityvar:
#            from: inputs/stripeInvoicesView
#            name: n_plans_total
#            select: count( distinct plan_id)
#        - entityvar:
#            from: inputs/stripeInvoicesView
#            name: n_paid_intervals
#            select: count( distinct invoices_id)
#            where: charges_created_timestamp is not null or charges_created_timestamp < to_timestamp_tz(replace('{{timestamp}}',' UTC'))
#        - inputvar:
#            from: inputs/stripeInvoicesView
#            name: subscriptions_renewal_count
#            select: sum(case when charges_amount > 0 then 1 else 0 end)
#            window:
#              partition_by:
#                - subscriptions_id
#        - entityvar:
#            from: inputs/stripeInvoicesView
#            name: n_max_renewals
#            select: case when max(subscriptions_renewal_count) = 0 then null else max(subscriptions_renewal_count) - 1 end
#        - entityvar:
#            from: inputs/stripeInvoicesView
#            name: distinct_plans_subscribed
#            select: array_agg(distinct plan_id)
#        - entityvar:
#            from: inputs/stripeInvoicesView
#            name: current_amount_due_subscriptions
#            select: sum(amount_due)
#            where: (charges_created_timestamp is null or charges_created_timestamp > to_timestamp_tz(replace('{{timestamp}}',' UTC'))) and (canceled_at is null or canceled_at > to_timestamp_tz(replace('{{timestamp}}',' UTC'))) and amount_due > 0
#        - entityvar:
#            from: inputs/stripeInvoicesView
#            name: amt_spent_subscriptions
#            select: sum(charges_amount) - sum(case when refund_amount is not null then refund_amount else 0 end)
#            where: invoices_id is not null
#        - entityvar:
#            from: inputs/stripeInvoicesView
#            name: first_subscription_time
#            select: min(charges_created_timestamp)
#            where: invoices_id is not null and (canceled_at is null or canceled_at > to_timestamp_tz(replace('{{timestamp}}',' UTC')))
#        - entityvar:
#            name: days_since_first_subscription
#            select: '{{ macro_datediff(''first_subscription_time'') }}'
#        - entityvar:
#            from: inputs/stripeInvoicesView
#            name: total_active_subscriptions
#            select: count( distinct subscriptions_id)
#            where: charges_amount > 0 and (canceled_at is null or canceled_at > to_timestamp_tz(replace('{{timestamp}}',' UTC')))
#        - entityvar:
#            from: inputs/stripeInvoicesView
#            name: total_active_plans
#            select: count( distinct plan_id)
#            where: charges_amount > 0 and (canceled_at is null or canceled_at > to_timestamp_tz(replace('{{timestamp}}',' UTC')))
#        - entityvar:
#            from: inputs/stripeInvoicesView
#            name: active_plan_intervals
#            select: array_agg(plan_interval)
#            where: charges_amount > 0 and (canceled_at is null or canceled_at > to_timestamp_tz(replace('{{timestamp}}',' UTC')))
#        - entityvar:
#            from: inputs/stripeInvoicesView
#            name: total_active_plan_amount
#            select: sum(plan_amount)
#            where: charges_amount > 0 and (canceled_at is null or canceled_at > to_timestamp_tz(replace('{{timestamp}}',' UTC')))
#  - name: subscription_stripe_features
#    model_type: feature_table_model
#    model_spec:
#      entity_key: subscription
#      features:
#        - days_since_first_sale
#        - days_since_last_purchase
#        - total_sales
#      macros:
#        - inputs:
#            - timestamp_col
#          name: macro_datediff
#          value: datediff(day, date({{timestamp_col}}), to_timestamp_tz(replace('{{timestamp}}',' UTC')))
#      validity_time: 24h
#      vars:
#        - entityvar:
#            from: inputs/stripeCharges
#            name: first_sale_time
#            select: min(created)
#            where: status = 'succeeded'
#        - entityvar:
#            name: days_since_first_sale
#            select: '{{ macro_datediff(''first_sale_time'') }}'
#        - entityvar:
#            from: inputs/stripeCharges
#            name: last_purchase_time
#            select: max(created)
#            where: status = 'succeeded'
#        - entityvar:
#            name: days_since_last_purchase
#            select: '{{ macro_datediff(''last_purchase_time'') }}'
#        - entityvar:
#            from: inputs/stripeBalanceHistory
#            name: total_sales
#            select: sum(amount)
#            where: type = 'charge'
