models:
  - model_spec:
      edge_sources:
        - inputs/rsIdentifies
        - inputs/rsTracks
      entity_key: user
      main_id_type: main_id
      validity_time: 24h
    model_type: id_stitcher
    name: domain_profile_id_stitcher
  - model_spec:
      entity_key: user
      features:
        - user_lifespan
        - days_active
      validity_time: 24h
      vars:
        - entityvar:
            from: inputs/rsTracks
            name: first_seen
            select: min(to_date(timestamp))
        - entityvar:
            from: inputs/rsTracks
            name: last_seen
            select: max(to_date(timestamp))
        - entityvar:
            description: Life Time Value of a customer
            name: user_lifespan
            select: last_seen - first_seen
        - entityvar:
            description: No. of days a customer was active
            from: inputs/rsTracks
            name: days_active
            select: count(distinct to_date(timestamp))
    model_type: feature_table_model
    name: domain_profile
