models:
  - model_spec:
      edge_sources:
        - inputs/stripeCustomers
        - inputs/stripeCharges
        - inputs/stripeInvoices
        - inputs/stripeBalanceHistory
        - inputs/stripeSubscriptions
        - inputs/stripeRefunds
        - inputs/stripeInvoicesView
      entity_key: customer
      main_id_type: main_id
      validity_time: 24h
    model_type: id_stitcher
    name: customer_stripe_id_stitcher
